(()=>{
const W=480,H=720,SPD=230,BOUNCE=-455,SY=620;
const adapter={gameplayStart(){},gameplayStop(){},submitScore(s){console.info('[score]',s)}};
function gen(o){const r=[],rng=Math.random;let y=o.startY,px=o.startX??o.worldWidth/2;for(let i=0;i<o.count;i++){y-=o.minGap+rng()*(o.maxGap-o.minGap);const w=o.minWidth+rng()*(o.maxWidth-o.minWidth),lo=o.margin+w/2,hi=o.worldWidth-o.margin-w/2;let a=lo,b=hi;if(o.maxHorizontalDelta!==undefined){a=Math.max(lo,px-o.maxHorizontalDelta);b=Math.min(hi,px+o.maxHorizontalDelta)}const x=a<=b?a+rng()*(b-a):Math.min(hi,Math.max(lo,px));r.push({x,y,width:w});px=x}return r}
class GameScene extends Phaser.Scene{
constructor(){super('game');this.hazardY=H+80;this.score=0;this.bestScore=0;this.isDead=false;this.touchDirection=0}
create(){
this.physics.world.setBounds(0,-6000,W,6720);this.cameras.main.setBounds(0,-6000,W,6720);this.cameras.main.setBackgroundColor('#151515');
this.platforms=this.physics.add.staticGroup();this.mkplat(W/2,675,220);
for(const p of gen({worldWidth:W,startY:630,count:62,minGap:68,maxGap:92,minWidth:110,maxWidth:180,margin:18,startX:W/2,maxHorizontalDelta:110}))this.mkplat(p.x,p.y,p.width);
this.player=this.physics.add.sprite(W/2,SY,'__WHITE');this.player.setDisplaySize(28,28);this.player.setTint(0xf5e663);this.player.setCollideWorldBounds(true);this.player.body.setSize(28,28);this.player.setVelocityY(BOUNCE);
this.physics.add.collider(this.player,this.platforms,()=>{if(!this.isDead)this.player.setVelocityY(BOUNCE)});
this.hazard=this.add.rectangle(W/2,this.hazardY+2500,W,5000,0x090909,.96).setDepth(4);
this.cameras.main.startFollow(this.player,true,.08,.08,0,190);
this.scoreText=this.add.text(16,14,'0 m',{fontSize:'26px',color:'#fff',fontStyle:'bold'}).setScrollFactor(0).setDepth(10);
this.bestScore=Number(localStorage.getItem('agf:g001:best')??0);this.bestText=this.add.text(16,48,`best ${this.bestScore} m`,{fontSize:'14px',color:'#bdbdbd'}).setScrollFactor(0).setDepth(10);
this.helpText=this.add.text(W/2,118,'STEER  ← →  /  A D\nLAND ON WHITE PLATFORMS\nYOU BOUNCE AUTOMATICALLY',{fontSize:'17px',color:'#fff',align:'center',backgroundColor:'#000000aa',padding:{x:12,y:9}}).setOrigin(.5).setScrollFactor(0).setDepth(10);
this.time.delayedCall(6000,()=>this.tweens.add({targets:this.helpText,alpha:0,duration:700}));
this.cursors=this.input.keyboard.createCursorKeys();this.keyA=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.A);this.keyD=this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.D);
this.input.on('pointerdown',p=>{this.touchDirection=p.x<this.scale.width/2?-1:1});this.input.on('pointerup',()=>this.touchDirection=0);this.input.on('pointerout',()=>this.touchDirection=0);adapter.gameplayStart();
}
update(_,dt){if(this.isDead)return;const l=this.cursors.left.isDown||this.keyA.isDown||this.touchDirection<0,r=this.cursors.right.isDown||this.keyD.isDown||this.touchDirection>0;if(l===r)this.player.setVelocityX(0);else this.player.setVelocityX(l?-SPD:SPD);this.hazardY-=this.hspeed()*(dt/1000);this.hazard.setY(this.hazardY+2500);const climbed=Math.max(0,Math.floor((SY-this.player.y)/10));if(climbed>this.score){this.score=climbed;this.scoreText.setText(`${this.score} m`)}if(this.player.y>this.hazardY+8)this.die()}
hspeed(){return 28+Math.min(32,this.score*.055)}
mkplat(x,y,w){const p=this.add.rectangle(x,y,w,14,0xe6e6e6);this.physics.add.existing(p,true);const b=p.body;b.checkCollision.up=true;b.checkCollision.down=false;b.checkCollision.left=false;b.checkCollision.right=false;this.platforms.add(p)}
die(){this.isDead=true;this.player.setTint(0x777777);this.player.setVelocity(0,0);this.player.body.enable=false;adapter.gameplayStop();adapter.submitScore(this.score);if(this.score>this.bestScore){this.bestScore=this.score;localStorage.setItem('agf:g001:best',String(this.bestScore));this.bestText.setText(`best ${this.bestScore} m`)}this.events.emit('run-ended',this.score)}
}
class OverlayScene extends Phaser.Scene{
constructor(){super('overlay');this.lastScore=0}
create(){const f=this.add.text(466,18,'feedback',{fontSize:'14px',color:'#fff',backgroundColor:'#333333cc',padding:{x:8,y:5}}).setOrigin(1,0).setInteractive({useHandCursor:true});f.on('pointerdown',()=>this.feedback());const g=this.scene.get('game');g.events.on('run-ended',s=>{this.lastScore=s;this.over(s)})}
over(s){this.gameOverPanel?.destroy(true);const p=this.add.rectangle(240,360,330,250,0,.88),t=this.add.text(240,292,'THE LIGHT WENT OUT',{fontSize:'24px',color:'#fff',fontStyle:'bold'}).setOrigin(.5),st=this.add.text(240,334,`${s} m`,{fontSize:'30px',color:'#f5e663'}).setOrigin(.5),r=this.add.text(240,395,'RETRY',{fontSize:'22px',color:'#111',backgroundColor:'#f5e663',padding:{x:30,y:12}}).setOrigin(.5).setInteractive({useHandCursor:true}),i=this.add.text(240,449,'suggest a feature',{fontSize:'15px',color:'#ddd'}).setOrigin(.5).setInteractive({useHandCursor:true});r.on('pointerdown',()=>{this.gameOverPanel?.destroy(true);this.scene.stop('game');this.scene.launch('game')});i.on('pointerdown',()=>this.feedback());this.gameOverPanel=this.add.container(0,0,[p,t,st,r,i])}
feedback(){if(this.feedbackPanel)return;const p=this.add.rectangle(240,350,380,300,0x101010,.97),t=this.add.text(240,235,'What should we add?',{fontSize:'22px',color:'#fff',fontStyle:'bold'}).setOrigin(.5),h=this.add.text(240,270,'bugs, features, weird ideas — all welcome',{fontSize:'13px',color:'#aaa'}).setOrigin(.5),input=document.createElement('textarea');input.maxLength=600;input.placeholder='I wish the game had…';Object.assign(input.style,{width:'300px',height:'90px',resize:'none',font:'16px system-ui',padding:'10px',borderRadius:'8px',border:'1px solid #555',background:'#202020',color:'#fff'});const d=this.add.dom(240,340,input),send=this.add.text(190,430,'SEND',{fontSize:'16px',color:'#111',backgroundColor:'#f5e663',padding:{x:18,y:9}}).setOrigin(.5).setInteractive({useHandCursor:true}),close=this.add.text(290,430,'CLOSE',{fontSize:'16px',color:'#ddd',backgroundColor:'#333',padding:{x:18,y:9}}).setOrigin(.5).setInteractive({useHandCursor:true}),status=this.add.text(240,474,'',{fontSize:'13px',color:'#aaa'}).setOrigin(.5),destroy=()=>{this.feedbackPanel?.destroy(true);this.feedbackPanel=undefined};close.on('pointerdown',destroy);send.on('pointerdown',()=>{const m=input.value.trim();if(!m){status.setText('write something first :)');return}const k='agf:g001:feedback',a=JSON.parse(localStorage.getItem(k)??'[]');a.push({gameId:'G001',build:'0.1.0-repair01-playground',message:m,score:this.lastScore,createdAt:new Date().toISOString()});localStorage.setItem(k,JSON.stringify(a.slice(-50)));status.setText('thank you ♥');this.time.delayedCall(650,destroy)});this.feedbackPanel=this.add.container(0,0,[p,t,h,d,send,close,status]);d.setDepth(30)}
}
new Phaser.Game({type:Phaser.AUTO,parent:'app',width:W,height:H,backgroundColor:'#151515',physics:{default:'arcade',arcade:{gravity:{x:0,y:950},debug:false}},dom:{createContainer:true},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[GameScene,OverlayScene]});
})();
